import "./globals.css";

import { Montserrat } from "next/font/google";

import { Providers } from "@/components";

const font = Montserrat({ subsets: ["latin"] });

export const metadata = {
    title: "NewsBytes",
    description: "Generated by create next app",

};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <Providers>
                    { children }
                </Providers>
            </body>
        </html>
    );
}
